name: fiapdonate

services:
  fiapdonate-services:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fiapdonate-services
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      CampaignApi__BaseUrl: http://fiapdonate-campaign:8080
      UsersApi__BaseUrl: http://fiapdonate-users:8080
      ReceiverApi__BaseUrl: http://fiapdonate-receiver:8080
      WorkerApi__BaseUrl: http://fiapdonate-worker:8080
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Port: 5672
      RabbitMQ__VirtualHost: /
    secrets:
      - rabbitmq_user
      - rabbitmq_password
    ports:
      - "8090:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - fiapdonate-network

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: fiapdonate-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    secrets:
      - rabbitmq_user
      - rabbitmq_password
    command:
      - /bin/sh
      - -c
      - |
        export RABBITMQ_DEFAULT_USER="$(cat /run/secrets/rabbitmq_user)"
        export RABBITMQ_DEFAULT_PASS="$(cat /run/secrets/rabbitmq_password)"
        exec docker-entrypoint.sh rabbitmq-server
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - fiapdonate-network

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: fiapdonate-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    networks:
      - fiapdonate-network

  grafana:
    image: grafana/grafana:11.1.0
    container_name: fiapdonate-grafana
    ports:
      - "3000:3000"
    secrets:
      - grafana_admin_password
    command:
      - /bin/sh
      - -c
      - |
        export GF_SECURITY_ADMIN_USER="admin"
        export GF_SECURITY_ADMIN_PASSWORD="$(cat /run/secrets/grafana_admin_password)"
        exec /run.sh
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus
    networks:
      - fiapdonate-network

secrets:
  rabbitmq_user:
    file: ./secrets/rabbitmq_user.txt
  rabbitmq_password:
    file: ./secrets/rabbitmq_password.txt
  grafana_admin_password:
    file: ./secrets/grafana_admin_password.txt

networks:
  fiapdonate-network:
    driver: bridge
