apiVersion: v1
kind: Secret
metadata:
  name: fiapdonate-secrets
  namespace: fiapdonate
type: Opaque
stringData:
  JWT_KEY: changeme-for-local-dev
  RabbitMQ__User: guest
  RabbitMQ__Password: guest
  GRAFANA_ADMIN_USER: admin
  GRAFANA_ADMIN_PASSWORD: admin
