apiVersion: v1
kind: Secret
metadata:
  name: fiapdonate-sqlserver-secrets
  namespace: fiapdonate
type: Opaque
stringData:
  MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  namespace: fiapdonate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fiapdonate-sqlserver-secrets
                  key: MSSQL_SA_PASSWORD
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "$MSSQL_SA_PASSWORD" -Q "SELECT 1" || exit 1
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "$MSSQL_SA_PASSWORD" -Q "SELECT 1" || exit 1
            initialDelaySeconds: 30
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver
  namespace: fiapdonate
spec:
  selector:
    app: sqlserver
  ports:
    - name: sql
      port: 1433
      targetPort: 1433
  type: ClusterIP
