apiVersion: v1
kind: ConfigMap
metadata:
  name: fiapdonate-services-config
  namespace: fiapdonate
data:
  ASPNETCORE_ENVIRONMENT: Development
  CampaignApi__BaseUrl: http://fiapdonatecampaign:8080
  UsersApi__BaseUrl: http://fiapdonate-users:8080
  ReceiverApi__BaseUrl: http://fiapdonate-receiver:8080
  WorkerApi__BaseUrl: http://fiapdonate-worker:8080
  RabbitMQ__Host: rabbitmq
  RabbitMQ__Port: "5672"
  RabbitMQ__VirtualHost: "/"
  RabbitMQ__User: fiapdonate
  RabbitMq__Host: rabbitmq
  RabbitMq__VirtualHost: "/"
  RabbitMq__Username: fiapdonate
  JWT_ISSUER: fiapdonate
  JWT_AUDIENCE: fiapdonate-clients
