apiVersion: v1
kind: ConfigMap
metadata:
  name: fiapdonate-receiver-config
  namespace: fiapdonate
data:
  RabbitMq__Host: rabbitmq
  RabbitMq__VirtualHost: "/"
  RabbitMq__Username: fiapdonate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiapdonate-receiver
  namespace: fiapdonate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiapdonate-receiver
  template:
    metadata:
      labels:
        app: fiapdonate-receiver
    spec:
      containers:
        - name: receiver
          image: fiapdonatereceiver-worker:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: fiapdonate-receiver-config
            - secretRef:
                name: fiapdonate-receiver-secrets
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: fiapdonate-receiver
  namespace: fiapdonate
spec:
  selector:
    app: fiapdonate-receiver
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
