apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: fiapdonate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.13-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                configMapKeyRef:
                  name: fiapdonate-services-config
                  key: RabbitMQ__User
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  name: fiapdonate-secrets
                  key: RabbitMQ__Password
          volumeMounts:
            - name: rabbitmq-definitions
              mountPath: /etc/rabbitmq/definitions.json
              subPath: definitions.json
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - until rabbitmq-diagnostics -q ping; do sleep 1; done; rabbitmqctl import_definitions /etc/rabbitmq/definitions.json
          readinessProbe:
            exec:
              - command: ["rabbitmq-diagnostics", "-q", "ping"]
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec:
              - command: ["rabbitmq-diagnostics", "-q", "ping"]
            initialDelaySeconds: 20
            periodSeconds: 15
      volumes:
        - name: rabbitmq-definitions
          configMap:
            name: rabbitmq-definitions
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: fiapdonate
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-definitions
  namespace: fiapdonate
data:
  definitions.json: |
    {
      "vhosts": [{"name": "/"}],
      "queues": [{"name": "doacao-recebida-queue", "vhost": "/", "durable": true, "auto_delete": false, "arguments": {}}],
      "exchanges": [{"name": "FiapDonateWorker.Api.Events:DoacaoRecebidaEvent", "vhost": "/", "type": "fanout", "durable": true, "auto_delete": false, "internal": false, "arguments": {}}],
      "bindings": [{"source": "FiapDonateWorker.Api.Events:DoacaoRecebidaEvent", "vhost": "/", "destination": "doacao-recebida-queue", "destination_type": "queue", "routing_key": "", "arguments": {}}]
    }
