apiVersion: v1
kind: Secret
metadata:
  name: fiapdonate-postgres-secrets
  namespace: fiapdonate
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: fiapdonate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: conexao_solidaria
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fiapdonate-postgres-secrets
                  key: POSTGRES_PASSWORD
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U postgres -d conexao_solidaria
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U postgres -d conexao_solidaria
            initialDelaySeconds: 20
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: fiapdonate
spec:
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  type: ClusterIP
